language: perl
arch:
 - arm64
matrix:
 include:
  - dist: xenial
    perl: 5.24
  - dist: bionic
    perl: 5.26
    env: DISPLAY=:123 WITH_X11=yes
  - dist: focal
    perl: 5.32
  - dist: focal
    perl: 5.32
    env: DISPLAY=:123 WITH_X11=yes USE_SYSTEM_PERL
#matrix:
# include:
#  - perl: "5.26"
#    env: DISPLAY=:123 WITH_X11=yes
#  - perl: "5.22"
#    env: DISPLAY=:123 WITH_X11=yes
#  - perl: "5.20"
#    env: WITH_X11=no
#  - perl: "5.18"
#    env: DISPLAY=:123 WITH_X11=yes USE_SYSTEM_PERL
#  - perl: "5.18"
#    env: DISPLAY=:123 WITH_X11=yes
#    dist: trusty
#  - perl: "5.16"
#    env: DISPLAY=:123 WITH_X11=yes
#  - perl: "5.14"
#    env: DISPLAY=:123 WITH_X11=yes
#  - perl: "5.12"
#    env: DISPLAY=:123 WITH_X11=yes
#  - perl: "5.10"
#    env: DISPLAY=:123 WITH_X11=yes
#  - perl: "5.8"
#    env: DISPLAY=:123 WITH_X11=yes

addons:
 apt:
  packages:
   - xvfb
   - xfonts-base
   - xterm
   - rxvt
   - rxvt-unicode

before_install:
 - if [ "$USE_SYSTEM_PERL" = 1 ]; then perlbrew off; fi

script:
 - export HARNESS_OPTIONS=j4:c HARNESS_TIMER=1
 - 'if [ "$WITH_X11" = "yes" ]; then perl Makefile.PL && env HARNESS_TIMER=1 xvfb-run --auto-servernum make test; fi'
 - 'if [ "$WITH_X11" = "no"  ]; then perl Makefile.PL && env HARNESS_TIMER=1                           make test; fi'

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/
