language: perl
matrix:
 include:
  - perl: "5.22"
    env: DISPLAY=:123 WITH_X11=yes
  - perl: "5.20"
    env: DISPLAY=:123 WITH_X11=yes
  - perl: "5.18"
    env: WITH_X11=no
  - perl: "5.18"
    env: DISPLAY=:123 WITH_X11=yes
  - perl: "5.18"
    env: DISPLAY=:123 WITH_X11=yes
    dist: trusty
  - perl: "5.16"
    env: DISPLAY=:123 WITH_X11=yes
  - perl: "5.14"
    env: DISPLAY=:123 WITH_X11=yes
  - perl: "5.12"
    env: DISPLAY=:123 WITH_X11=yes
  - perl: "5.10"
    env: DISPLAY=:123 WITH_X11=yes
  - perl: "5.8"
    env: DISPLAY=:123 WITH_X11=yes

addons:
 apt:
  packages:
   - xvfb
   - xterm
   - rxvt
   - rxvt-unicode

script:
 - '[ "$WITH_X11" = "yes" ] && (perl Makefile.PL && env HARNESS_TIMER=1 xvfb-run --auto-servernum make test) || true'
 - '[ "$WITH_X11" = ""    ] && (perl Makefile.PL && env HARNESS_TIMER=1                           make test) || true'

sudo: true

branches:
 except:
  - /appveyor/
