name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'
  pull_request:

jobs:

  test_on_host:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       include:
         - os: 'ubuntu-22.04'
         - os: 'ubuntu-24.04'
    steps:
    - name: apt hacks
      # /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
      run: |
        sudo rm -f /etc/apt/sources.list.d/*.list
        sudo apt-get update -qq
    - uses: taiki-e/checkout-action@v1
    - name: Build
      run: |
        perl Makefile.PL
        make distcheck
    - name: Test without X11
      run: |
        HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest
    - name: Test with X11
      run: |
        sudo apt-get install -q --no-install-recommends xvfb xauth xfonts-base xterm rxvt-unicode libterm-readkey-perl
        HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c xvfb-run --auto-servernum make disttest

  test_in_container_dists:
    name: Container tests with ${{ matrix.dist }}:${{ matrix.distver }}
    runs-on: ubuntu-latest
    container: ${{ matrix.dist }}:${{ matrix.distver }}
    strategy:
      matrix:
        include:
          - dist:    debian
            distver: jessie
          - dist:    debian
            distver: stretch
          - dist:    debian
            distver: buster
          - dist:    debian
            distver: bullseye
          - dist:    ubuntu
            distver: 16.04
          - dist:    ubuntu
            distver: 20.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - name: apt hacks
      run: |
        set -e
        CODENAME=$(perl -nle '/^VERSION_CODENAME="?([^"]+)/ and $codename=$1; /^VERSION="\d+ \((.*)\)/ and $maybe_codename=$1; END { print $codename || $maybe_codename }' /etc/os-release)
        case "$CODENAME" in
          wheezy|jessie|stretch)
            echo "APT::Get::AllowUnauthenticated 1;" > /etc/apt/apt.conf.d/02allow-unsigned
            echo "deb [check-valid-until=no] http://archive.debian.org/debian $CODENAME main"                   >  /etc/apt/sources.list
            echo "deb [check-valid-until=no] http://archive.debian.org/debian-security/ $CODENAME/updates main" >> /etc/apt/sources.list
            ;;
        esac
    - uses: taiki-e/checkout-action@v1
    - name: Install X11 stuff on Debian
      run: |
        set -e
        apt-get update -qq
        apt-get install -q --no-install-recommends -y make xvfb xauth xfonts-base xterm rxvt-unicode libterm-readkey-perl
    - name: Build and test
      run: |
        set -e
        perl Makefile.PL
        make distcheck
        HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c xvfb-run --auto-servernum make disttest
